packages:
  - docs
  - playground
  - examples/**
  - packages/**

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - vue-demi

peerDependencyRules:
  ignoreMissing:
    - vue
    - webpack
