packages:
  - docs
  - playground
  - examples/**
  - packages/**

ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - vue
    - webpack
