name: "\U0001F41E Bug report"
description: Create a report to help us improve Nuxt
labels: ['type: bug']
body:
  - type: markdown
    attributes:
      value: "
        ### Search for existing issues

        Please carefully [search for related issues (open and closed)](https://github.com/nuxt-modules/storybook/issues?q=is%3Aissue) and make sure you're not submitting a duplicate issue.
        If you find anything that seems like the same bug, it's much better to comment on an existing thread than create a duplicate.

        ### Check nightly builds

        We are constantly improving the module and it's possible that the issue you're experiencing has already been fixed in the latest nightly build.
        Please try to reproduce the issue with the [latest nightly build](https://storybook.nuxtjs.org/getting-started/setup#nightly-builds) and see if it still persists.
        "
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: You can use `npx nuxi info` to fill this section
      placeholder: Environment
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description:
        It is important to provide a minimal reproduction of the issue you're experiencing. This makes it easier to understand the problem and to find a solution.
        Issues without a reproduction might be closed immediately.

        The best way to create a minimal reproduction is by modifying the [Showcase example](https://github.com/nuxt-modules/storybook/tree/main/examples/showcase),
        and open a PR with the minimal changes that reproduce the issue.
        Alternatively, you can use the [StackBlitz template](https://stackblitz.com/github/nuxt-modules/storybook/tree/main/examples/starter) to create a minimal reproduction.
      placeholder: URL to the reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
        Please try not to insert an image but copy paste the error text.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here
