name: ci-examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    name: ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: Playground
            buildScript: dev:build
            storybookBuildScript: playground:storybook:build
            projectToken: chpt_d7cf5e98426e11e
          - package: Starter
            buildScript: example:starter:build
            storybookBuildScript: example:starter:storybook:build
            projectToken: chpt_dc04103f8a32bfa
          - package: Tailwind
            buildScript: example:tailwind:build
            storybookBuildScript: example:tailwind:storybook:build
            projectToken: chpt_fbfe47dc27d4064
          - package: Showcase
            buildScript: example:showcase:build
            storybookBuildScript: example:showcase:storybook:build
            projectToken: chpt_a53adf402cb628c
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build example
        run: pnpm ${{ matrix.buildScript }}

      - name: Publish and test example
        uses: chromaui/action@1bbb5819252d9782cb7d77122d9becae467def18 # v16.10.1
        with:
          # Don't wait until Chromatic verified the build
          # exitOnceUploaded: true
          projectToken: ${{ matrix.projectToken }}
          buildScriptName: ${{ matrix.storybookBuildScript }}
          # Fail workflow if changes are found
          exitZeroOnChanges: false
          debug: true
