name: release-nightly

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'nuxt' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Prepare build environment
        run: pnpm dev:prepare

      - name: Build
        run: pnpm build

      - name: 📦 release pkg.pr.new
        run: pnpm pkg-pr-new publish
